### ISSUE TITLE
Poll heard through TX when WSJT or JTDX

### ISSUE THREAD

**Issue by Jokke-moose** [VE3NEA/OmniRig#10]
Hi,
I noticed the poll intervall ticks are heard through the TX. And only when using JTDX and WSJT for instance. 
If I just use manual PTT during voice, it is not heard. 
Rgds,
Johan

**Comment by VE3NEA** [comment]
Johan,

OmniRig does not work with the audio system. The ticks you hear is a hardware problem, interaction between the COM and audio cables. To fix this, eliminate the [pin 1](https://www.ranecommercial.com/legacy/note165.html) problem, break the [ground loops](https://help.campbellsci.com/CR6/Content/shared/Maintain/Troubleshooting/ground-loops.htm), use shielded cables - google for the detailed instructions.
